---
name: Pull Request Workflow | Github Actions Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/**'

jobs:
  validate:
    name: Validate Workflow Files
    uses: eingram-homelab/reusable_workflows/.github/workflows/_validate-workflow.yaml@main
